# 100
HTTP_STATUS_CONTINUE                        = 100_u32
HTTP_STATUS_SWITCHING_PROTOCOLS             = 101_u32
# 200
HTTP_STATUS_OK                              = 200_u32 # This one is my favorite.
HTTP_STATUS_CREATED                         = 201_u32
HTTP_STATUS_ACCEPTED                        = 202_u32
HTTP_STATUS_NON_AUTHORITATIVE               = 203_u32
HTTP_STATUS_NO_CONTENT                      = 204_u32
HTTP_STATUS_RESET_CONTENT                   = 205_u32
HTTP_STATUS_PARTIAL_CONTENT                 = 206_u32
HTTP_STATUS_IM_USED                         = 226_u32
# 300
HTTP_STATUS_MULTIPLE_CHOICES                = 300_u32
HTTP_STATUS_MOVED_PERMANENTLY               = 301_u32
HTTP_STATUS_FOUND                           = 302_u32
HTTP_STATUS_SEE_OTHER                       = 303_u32
HTTP_STATUS_NOT_MODIFIED                    = 304_u32
HTTP_STATUS_USE_PROXY                       = 305_u32
HTTP_STATUS_TEMPORARY_REDIRECT              = 307_u32
HTTP_STATUS_PERMANENT_REDIRECT              = 308_u32
# 400
HTTP_STATUS_BAD_REQUEST                     = 400_u32
HTTP_STATUS_UNAUTHORIZED                    = 401_u32
HTTP_STATUS_PAYMENT_REQUIRED                = 402_u32
HTTP_STATUS_FORBIDDEN                       = 403_u32
HTTP_STATUS_NOT_FOUND                       = 404_u32
HTTP_STATUS_METHOD_NOT_ALLOWED              = 405_u32
HTTP_STATUS_NOT_ACCEPTABLE                  = 406_u32
HTTP_STATUS_PROXY_AUTH_REQUIRED             = 407_u32
HTTP_STATUS_REQUEST_TIMEOUT                 = 408_u32
HTTP_STATUS_CONFLICT                        = 409_u32
HTTP_STATUS_GONE                            = 410_u32
HTTP_STATUS_LENGTH_REQUIRED                 = 411_u32
HTTP_STATUS_PRECONDITION_FAILED             = 412_u32
HTTP_STATUS_REQUEST_ENTITY_TOO_LARGE        = 413_u32
HTTP_STATUS_REQUEST_URI_TOO_LONG            = 414_u32
HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE          = 415_u32
HTTP_STATUS_REQUESTED_RANGE_NOT_SATIFIABLE  = 416_u32
HTTP_STATUS_EXPECTATION_FAILE               = 417_u32
HTTP_STATUS_MISDIRECTED_REQUEST             = 421_u32
HTTP_STATUS_LOCKED                          = 423_u32
HTTP_STATUS_UPGRADE_REQUIRED                = 426_u32
HTTP_STATUS_PRECONDITION_REQUIRED           = 428_u32
HTTP_STATUS_TOO_MANY_REQUESTS               = 429_u32
HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431_u32
HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS   = 451_u32
# 500
HTTP_STATUS_INTERNAL_SERVER_ERROR           = 500_u32
HTTP_STATUS_NOT_IMPLEMENTED                 = 501_u32
HTTP_STATUS_BAD_GATEWAY                     = 502_u32
HTTP_STATUS_SERVICE_UNAVAILABLE             = 503_u32
HTTP_STATUS_GATEWAY_TIMEOUT                 = 504_u32
HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED      = 505_u32
HTTP_STATUS_VARIANT_ALSO_NEGOTIATES         = 506_u32
HTTP_STATUS_NOT_EXTENDED                    = 510_u32
